### ISSUE TITLE
Add missing validator info

### ISSUE THREAD

**Issue by onmax** [onmax/nimiq-validator-trust-score#12]
Right now, the validators provide these details:

```json
{
  "name": "Optional. The name of the validator, by default it is the address",
  "description": "Optional. A description of the validator",
  "website": "Optional. The website of the validator.",
  "address": "NQXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX XXXX",
  "icon": "Optional. A base64 encoded SVG icon. By default identicon is used.",
  "fee": -1,
  "payoutType": "none"
}
```

However, I am considering adding a few extra fields required for some of the designs I am working on to explain to users about staking and would like your feedback before moving forward. Here's what I am thinking:

## `accentColor`

An optional color to align with the validator's branding, defaulting to the identicon background color if left blank.

This could help keep the overall look and feel consistent. Check out an example here:

![Image](https://github.com/user-attachments/assets/af65be32-6c68-4e9f-97c8-8a280991ba85)

## `payoutFrecuency`

An optional string to indicate the payout schedule. This could be helpful for users to know when to expect rewards. Here are some examples:

- "Last day of the month"
- "Twice a week"
- "once every 3 full moons"

## `contact`

An **optional** field allowing validators to share contact details so users can easily get in touch. The structure would look like this:

```json
{
  "contact": {
     "telegram": "@me",
     "x": "@me",
     "bluesky": "@me",
     "email": "example@me.com",
     "discordInvitationLink": "join-our-discord.com",
}
```

Currently, there’s no direct way for users to contact their validators, so this addition could enhance communication. The structure of the contact will need to be discussed as well.

**Comment by Eligioo** [comment]
I think all three options would add value here. Adding those fields would be backwards compatible with the current object 👍

**Comment by Albermonte** [comment]
`accentColor`: RGB, HEX, HLS?
`contact`: do we limit to those or leave it open for more socials like instagram, reddit, facebook?

**Comment by onmax** [comment]
> accentColor: RGB, HEX, HLS?

hex

> contact: do we limit to those or leave it open for more socials like instagram, reddit, facebook?

i would say to leave it static. we can add the ones you mentioned as well

**Comment by sisou** [comment]
Nice effort! I agree these are valuable and backward-compatible fields!

I also agree on the HEX color format and adding the other socials, as all socials are typed as optional, right?
